/*
 * This file is generated by jOOQ.
 */
package by.gsu.domain.tables.records;


import by.gsu.domain.tables.Note;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NoteRecord extends UpdatableRecordImpl<NoteRecord> implements Record5<Integer, String, String, String, String> {

    private static final long serialVersionUID = -1988922640;

    /**
     * Setter for <code>note.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>note.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>note.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>note.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>note.shortDescription</code>.
     */
    public void setShortdescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>note.shortDescription</code>.
     */
    public String getShortdescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>note.startDate</code>.
     */
    public void setStartdate(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>note.startDate</code>.
     */
    public String getStartdate() {
        return (String) get(3);
    }

    /**
     * Setter for <code>note.endDate</code>.
     */
    public void setEnddate(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>note.endDate</code>.
     */
    public String getEnddate() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Note.NOTE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Note.NOTE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Note.NOTE.SHORTDESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Note.NOTE.STARTDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Note.NOTE.ENDDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getShortdescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getStartdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getEnddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getShortdescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStartdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getEnddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NoteRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NoteRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NoteRecord value3(String value) {
        setShortdescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NoteRecord value4(String value) {
        setStartdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NoteRecord value5(String value) {
        setEnddate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NoteRecord values(Integer value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NoteRecord
     */
    public NoteRecord() {
        super(Note.NOTE);
    }

    /**
     * Create a detached, initialised NoteRecord
     */
    public NoteRecord(Integer id, String name, String shortdescription, String startdate, String enddate) {
        super(Note.NOTE);

        set(0, id);
        set(1, name);
        set(2, shortdescription);
        set(3, startdate);
        set(4, enddate);
    }
}
